# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ashasanm
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: books-api
service: books-api-dev-books

stages:
  default:
    params:
      region: ap-southeast-2
      tableName: ${self:service}-${sls:stage}-books
      # Add this to handle different CORS origins
      allowedOrigin: "*" 

  prod:
    params:
      region: ap-southeast-2
      tableName: books-production-table
      # Tighten security for production
      allowedOrigin: "https://musical-crumble-09ee41.netlify.app"

provider:
  name: aws
  runtime: python3.12
  region: ${param:region}
  environment:
    DYNAMODB_TABLE: ${param:tableName}
    AWS_ACCOUNT_REGION: ${param:region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt BooksTable.Arn
  httpApi:
    cors:
      allowedOrigins:
        - "*" # this should be change to web app endpoint
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowedHeaders:
        - '*'

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.venv/**'
    - '!venv/**'
    - '!.git/**'
    - '!__pycache__/**'
    - '!.pytest_cache/**'

custom:
  pythonRequirements:
    slim: true
    strip: true          # Removes debug symbols from shared libraries (.so files)
    dockerizePip: true
    noDeploy:
      - boto3            # Lambda already has boto3; don't include it in zip
      - botocore

functions:
  api:
    handler: app.main.handler
    events:
      - httpApi:
          path: /api/books
          method: POST
      - httpApi:
          path: /api/books/{book_id}
          method: GET

resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: bookId
            AttributeType: S
        KeySchema:
          - AttributeName: bookId
            KeyType: HASH